package Lists.LinkedLists;

import CustomExceptions.EmptyListException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public abstract class LinkedListTest {

    protected LinkedList<Integer> list;

    protected abstract  LinkedList<Integer> createList();

    @BeforeEach
    public void setup() {
        list = createList();
    }

    @Test
    public void singleElementTest() throws EmptyListException {
        list.addFirst(1);
        assertEquals(1, list.first());
    }

    @Test
    public void singleElementRemoveTest() throws EmptyListException {
        list.addFirst(1);
        list.removeFirst();
        assertTrue(list.isEmpty());
    }

    // Some testcases generated by Chat-GPT:

    // --------------------------
    // Basic State Tests
    // --------------------------

    @Test
    void newListShouldBeEmpty() {
        assertTrue(list.isEmpty());
        assertEquals(0, list.size());
    }

    @Test
    void sizeShouldIncreaseAfterAddFirst() {
        list.addFirst(10);
        assertEquals(1, list.size());
        assertFalse(list.isEmpty());
    }

    @Test
    void sizeShouldIncreaseAfterAddLast() {
        list.addLast(20);
        assertEquals(1, list.size());
    }

    // --------------------------
    // First / Last Access Tests
    // --------------------------

    @Test
    void firstShouldReturnFirstElement() throws EmptyListException {
        list.addFirst(5);
        list.addLast(10);

        assertEquals(5, list.first());
    }

    @Test
    void lastShouldReturnLastElement() throws EmptyListException {
        list.addFirst(5);
        list.addLast(10);

        assertEquals(10, list.last());
    }

    @Test
    void firstOnEmptyListShouldThrowException() {
        assertThrows(EmptyListException.class, () -> list.first());
    }

    @Test
    void lastOnEmptyListShouldThrowException() {
        assertThrows(EmptyListException.class, () -> list.last());
    }

    // --------------------------
    // Remove Tests
    // --------------------------

    @Test
    void removeFirstShouldReturnCorrectElement() throws EmptyListException {
        list.addLast(1);
        list.addLast(2);

        assertEquals(1, list.removeFirst());
        assertEquals(1, list.size());
    }

    @Test
    void removeLastShouldReturnCorrectElement() throws EmptyListException {
        list.addLast(1);
        list.addLast(2);

        assertEquals(2, list.removeLast());
        assertEquals(1, list.size());
    }

    @Test
    void removeFirstOnEmptyShouldThrowException() {
        assertThrows(EmptyListException.class, () -> list.removeFirst());
    }

    @Test
    void removeLastOnEmptyShouldThrowException() {
        assertThrows(EmptyListException.class, () -> list.removeLast());
    }

    // --------------------------
    // Order Integrity Tests
    // --------------------------

    @Test
    void addFirstShouldReverseOrder() throws EmptyListException {
        list.addFirst(1);
        list.addFirst(2);
        list.addFirst(3);

        assertEquals(3, list.removeFirst());
        assertEquals(2, list.removeFirst());
        assertEquals(1, list.removeFirst());
    }

    @Test
    void addLastShouldPreserveInsertionOrder() throws EmptyListException {
        list.addLast(1);
        list.addLast(2);
        list.addLast(3);

        assertEquals(1, list.removeFirst());
        assertEquals(2, list.removeFirst());
        assertEquals(3, list.removeFirst());
    }

    @Test
    void mixedOperationsShouldMaintainCorrectStructure() throws EmptyListException {
        list.addFirst(2);   // [2]
        list.addFirst(1);   // [1,2]
        list.addLast(3);    // [1,2,3]
        list.addLast(4);    // [1,2,3,4]

        assertEquals(1, list.removeFirst()); // [2,3,4]
        assertEquals(4, list.removeLast());  // [2,3]

        assertEquals(2, list.first());
        assertEquals(3, list.last());
        assertEquals(2, list.size());
    }

    // --------------------------
    // Single Element Edge Case
    // --------------------------

    @Test
    void removingOnlyElementShouldMakeListEmpty() throws EmptyListException {
        list.addFirst(42);

        assertEquals(42, list.removeLast());
        assertTrue(list.isEmpty());
        assertEquals(0, list.size());
    }

    // --------------------------
    // Stress Consistency Test
    // --------------------------

    @Test
    void multipleAddsAndRemovesShouldMaintainCorrectSize() throws EmptyListException {
        for (int i = 0; i < 100; i++) {
            list.addLast(i);
        }

        assertEquals(100, list.size());

        for (int i = 0; i < 50; i++) {
            list.removeFirst();
        }

        assertEquals(50, list.size());

        for (int i = 0; i < 50; i++) {
            list.removeLast();
        }

        assertTrue(list.isEmpty());
    }
}